server:
  servlet:
    context-path: /api-car
spring:
  profiles:
    active: ${MY_PROFILE_NAME}
  datasource:
    url: jdbc:postgresql://${HOST}:${PORT:5432}/${DB_NAME}?currentSchema=${SCHEMA}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PAROL}
    hikari:
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000
      schema: ${SCHEMA}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true

  sql:
    init:
      schema-locations: ${SCHEMA}
  threads:
    virtual:
      enabled: true

course:
  name: ABB Tech Academy
  students: Asif, Vasif, Sajjad
  teacher: TeacherName
  address: Street Name
  child:
    country: CountryName
    city: CityName

